version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onetime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d onetime" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  backend:
    build: .
    restart: always
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/onetime
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy

  everest-mqtt:
    image: ghcr.io/everest/everest-demo/mqtt-server:latest
    networks:
      default:
        aliases:
          - mqtt-server

  everest-manager:
    build:
      context: ./reference_docs/repos/citrineos-core/Server/everest
      dockerfile: Dockerfile
      args:
        - EVEREST_IMAGE_TAG=latest
    ports:
      - 8888:8888
    depends_on:
      - everest-mqtt
      - backend
    environment:
      - MQTT_SERVER_ADDRESS=everest-mqtt
      - EVEREST_TARGET_URL=backend:8000/ocpp/
      - OCPP_VERSION=one
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  everest-nodered:
    image: ghcr.io/everest/everest-demo/nodered:latest
    depends_on:
      - everest-mqtt
    ports:
      - 1880:1880
    environment:
      - MQTT_SERVER_ADDRESS=everest-mqtt
      - FLOWS=/config/config-sil-two-evse-flow.json

volumes:
  postgres_data:
